# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_2_FULL.zip'
  WindowsRTCSDKX64: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x64)_v3_0_0_2_FULL.zip'

jobs:
- template: 'OpenLive-Android/open-live-template.yml'
  parameters:
    project: 'OpenLive-Android'
    name: 'OpenLive_Android'

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSSwiftOpenLive'
    workingDirectory: 'OpenLive-iOS'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSOCOpenLive'
    workingDirectory: 'OpenLive-iOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacSwiftOpenLive'
    workingDirectory: 'OpenLive-macOS'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacOCOpenLive'
    workingDirectory: 'OpenLive-macOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

#Windows MFC demo
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'WindowsOpenLiveMFC'
    workingDirectory: 'OpenLive-Windows-MFC'
    scheme: 'OpenLive-Windows-MFC'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0.2_FULL'
    Machine: 'win32'
    ReleasePath: 'Release'
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'WindowsOpenLiveMFC64'
    workingDirectory: 'OpenLive-Windows-MFC'
    scheme: 'OpenLive-Windows-MFC'
    sdkurl: $(WindowsRTCSDKX64)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0.2_FULL'
    Machine: 'x64'
    ReleasePath: 'x64/Release'