# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/3.0.0

pool:
  vmImage: 'macos-latest'

variables:
- group: AgoraKeys

jobs:
- template: 'OpenLive-Android/open-live-template.yml'
  parameters:
    project: 'OpenLive-Android'
    name: 'OpenLive_Android'
    vmImage: 'macos-latest'