# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''
  sdkurl: ''
  sdkunzipPath: ''
  Machine: ''
  ReleasePath: ''
  QtDir: ''
jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    variables:
      solution: '${{ parameters.workingDirectory }}/${{ parameters.solutionName }}'
      buildPlatform: ${{ parameters.Machine }}
      buildConfiguration: 'Release'
   
    steps:
      - script: echo "${{ parameters.sdkurl }}" && ls
      - powershell: cicd/scripts/downloadsdk.ps1 "${{ parameters.sdkurl }}"
   
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: ${{ parameters.sdkunzipPath }}/libs
          targetFolder: ${{ parameters.workingDirectory }}/libs
      - script: cd ${{ parameters.workingDirectory }}/ && ls
              
      - script: install-qt-win.cmd
        displayName: 'Install QT'

      - script: call build_release.bat "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build" ${{ parameters.QtDir }}
        displayName: 'build OpenLive-Windows'

      - script: cd ${{ parameters.workingDirectory }} && ls

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '${{ parameters.workingDirectory }}/${{ parameters.ReleasePath }}/'
          includeRootFolder: true 
          archiveType: 'zip'
          archiveFile: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          replaceExistingArchive: true
          
      - script: ls 
      - script: cd ${{ parameters.workingDirectory }} && ls
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          ArtifactName: ${{ parameters.displayName }}
      - template: github-release.yml
        parameters:
          displayName: ${{ parameters.displayName }}